@startuml Trabajo Practico Laboratorio - Sistema de Refrigeracion

!define MyFontColor #000000
!define MyBorderColor #800080
!define MyBackgroundColor #E6E6FA
!define MyArrowColor #800080

skinparam defaultFontName Arial
skinparam DefaultFontSize 13
skinparam Linetype ortho
skinparam Arrowcolor MyArrowColor
skinparam ArrowThickness 2
skinparam Classbordercolor MyBorderColor
skinparam ClassBorderThickness 2
skinparam ClassBackgroundColor MyBackgroundColor
skinparam Shadowing true
skinparam GroupInheritance 1
skinparam NoteBackgroundColor yellow
skinparam NoteBorderThickness 2

class Reactor{
    + calcularEnergiaTermica(temperatura:Number,porcentajeProduccion:Number):Number;
}

interface SistemasDeRegulacionTermica{
    + controlarTemperatura(temperatura:Number):void;
}

class BarraDeControl implements SistemasDeRegulacionTermica{
    - vidaUtil:Number;
    + getVidaUtil():Number;
    + setVidaUtil(TiempovidaUtil:Number):void;
    + controlarTemperatura(temperatura:Number):void;
    + getPorcentajeProduccion():Number;
}

class ComputadoraDeHomero{
    + activarMecanismoDeRefrigeracion(mecanismoRefrigeracion:SistemaDeRegulacionTermica):void;
    + getTemperatura():Number;
}

Reactor *-- BarraDeControl
Reactor o-- ComputadoraDeHomero

@enduml