@startuml DiagramaDeClases

skinparam defaultFontName Arial
skinparam DefaultFontSize 13
skinparam Linetype ortho
skinparam Arrowcolor darkred
skinparam ArrowThickness 2
skinparam Classbordercolor darkred
skinparam ClassBorderThickness 2
skinparam ClassBackgroundColor LightYellow
skinparam Shadowing true
skinparam GroupInheritance 1
skinparam NoteBackgroundColor yellow
skinparam NoteBorderThickness 2


class ComputadoraHomero{
    
}

class Central{
    
}

class Reactor{

}

interface Notificador {
    + enviarAlerta(temperatura: double, estado: Estado): void
}

class GeneradorVapor{

}

class TorreRefrigeracion{

}

class Condensador{

}

class Barras{
    
}

class SensoresDeControl{
    + recibirTemperatura();
    + avisarAHomero();
}

class Turbina{

}

class GeneradorElectrico{

}

Central *-- Reactor
Central *-- GeneradorVapor
GeneradorVapor *-- Turbina
GeneradorVapor *-- GeneradorElectrico
Central *-- TorreRefrigeracion
Central *-- Condensador
Reactor o-- Barras
Reactor o-l- SensoresDeControl
Notificador <|.. ComputadoraHomero
Notificador <.u. Reactor

@enduml