@startuml "Diagrama de secuencias Generar Energia"

group generarEnergia
    Usuario -> centralNuclear : generarEnergia()
    /'
    alt if temperatura !== undefined
        centralNuclear -> centralNuclear : setTemperaturaReactor()
    end
    '/
    loop i<Numero> times
        'try
        centralNuclear -> reactor : generarEnergiaTermica()
        reactor -> normal : procesarEnergiaTermica()
        centralNuclear -> centralNuclear : generarEnergiaElectrica()
        'end
    end
    'catch
    'end
end

actor computadoraHomero
actor computadoraTrabajadorX
actor Burns

@enduml