@startwbs Trabajo Practico Laboratorio

* Trabajo Practico
 * Codigo
  * Central Nuclear
   * Edificio de Contencion
    * Generador de Vapor
     * Funcion energiaTermica a vapor
     * Turbina
     * Generador 
     * Condensador
    * Torre de refrigeración
    * Reactor
     * Funcion iniciarReactor
     * Funcion mantenerReactor
     * Funcion detenerReactor
     * SensorTermico
     * BarrasDeControl
     * TurbinasDeRefrigeración (No implementado)
     * CapacidadReactor
     * TemperaturaReactor
     * Funcion temperatura
   * Combustible 
 * Tests Unitarios
  * Funcion cantEnergiaNeta
  * Funcion cantBarrasConsumidas
  * Funcion enviarNotificacion
  * Funcion verificarMecanismos
  * Funcion obtenerTemperatura
  * Funcion obtenerEnergiaNeta
 * Diagrama de clases
 * Diagramas de secuencias
  * Diagrama de secuencia 1
  * Diagrama de secuencia 2

@endwbs